### ISSUE TITLE
My 2 cents

### ISSUE THREAD

**Issue by bukzor** [asottile-archive/dumbconf#20]
I've got no skin in this game, so feel free to ignore all this; I won't feel bad.

1. Nix the multiple ways to write true/false/null. It's the opposite direction of what you did with trailing commas. I think the rule of thumb you want is; if it's eventually going to be in someone's styleguide / pre-commit hook, let's nip in the bud at a syntactic level. I vote for true/false/null.  N/A rather than null might be nice.
1. You might say the same applies to the double/single-quote strings.
1. Similarly, why do we want some writers to use lower and others uppercase hexadecimal? Let's capitalize, imo.
1. Same thing, let's exponent with lowercase e. Case-insensitivity lost the war, readability (via consistency) counts, and "there's more than one way to do it!" has proven to be a crappy feature.
1. You missed multiline strings. Let's do them with automatic textwrap.dedent, like ruby does!
1. IMO it's important for the spec to say that a parse/unparse cycle (can) reproduce the file exactly.
1. For a similar reason, you might want to specify your floating-point as Decimals rather than floats. (This actually *saves* space on the wire in the usual case. Give [msgpack](http://msgpack.org/index.html) a json string "0.1" and see its "compression" ratio!)
1. You probably need to address bytes vs unicode. If you want to stick close to json, strings are just unicode, otherwise you'll probably end up specifying a bytes notation.
1. You might want to railroad-diagram the thing, like what's done on json.org, just to prove to yourself that it has simplicity worthy of the "dumb" brand. I really believe the chief reason json won is its simplicity. If I were to fight this battle, I'd just add comments, barewords, optional trailing commas, and multiline strings and call it done.

By the way, how do I get ahold of you? Are you on freenode? Hangouts?

**Comment by asottile** [comment]
Hi friend :)

1. Sounds good -- I'd definitely like to work this out as early as possible (this in fact makes things *simpler* too)
2. I think having both is a plus, it allows things like `"I wasn't planning on escape sequences"` and `'This is a "good" idea'`
3. I just went with the python rules here, it's probably more difficult to reject them than it is to allow them -- shrugs (I'm not going to use them personally)
4. Same just went with python rules
5. I wasn't planning to implement them (mostly because they're difficult and stray too close to the hard-to-understand bits of yaml) -- maybe in a v2?
6. I think there's two things to spec here, one being the config language itself, the second being the parser/unparser -- and yes I agree that should definitely come into play of the spec of the parser/unparser :)
7. Interesting, I'll have to think about this a bit mostly because I haven't worked with `decimal` that much
8. Currently everything is unicode, I haven't thought about representing binary yet beyond presenting a bytestring as `"\x12\x13"` and requiring clients to `.encode('latin1')` after the fact -- perhaps a more first-class approach (such as `b'foo'`) is in order!
9. yeah, it's gotten a little bit smarter than "dumb" -- I actually plan to rename it before releasing and using it in the wild :)

Thanks for all the great feedback :)

I'm often on freenode (asottile), I'm also often on hangouts (I'll send you a message)

**Comment by asottile** [comment]
Here's for 1: https://github.com/asottile/dumbconf/pull/21

**Comment by bukzor** [comment]
Oh, I knew I forgot something: you should add the number underscoring like Java and Python have. It's great for readability in super long numbers.  `1_000_000_000_000`

The strictest form would require the underscores to not be at the beginning or end, and to have at least two digits between. Or you could just use `[0-9_]+`.

**Comment by asottile** [comment]
I'd have to write my own number parser at that point -- underscoring in numbers is a py36+ feature

**Comment by bukzor** [comment]
Oh I thought you were aiming to be cross language implementable, like JSON.

**Comment by asottile** [comment]
Probably in the future yes
